// AUTO-GENERATED by generate_gallery_data.py
// Do not edit manually. Run the script to regenerate.

const GALLERY_DATA = {

  "kolemasega-2015": {
    title:  "Kolemasega Basic School",
    meta:   "December 2015 \u00b7 Zaari, Upper East",
    folder: "images/projects/kolemasega-2015/",
    images: ["furniture.png"],
  },

  "frafra-2016": {
    title:  "Frafra Catholic School",
    meta:   "July 2016 \u00b7 Frafra, Upper East",
    folder: "images/projects/frafra-2016/",
    images: ["IMG-20160610-WA0009.jpg", "IMG-20160610-WA0012.jpg", "IMG-20160711-WA0006.jpg", "IMG-20160711-WA0007.jpg", "IMG-20160712-WA0014.jpg", "IMG-20160712-WA0015.jpg", "IMG-20160712-WA0016.jpg"],
  },

  "zaari-2017": {
    title:  "Zaari Primary School",
    meta:   "December 2017 \u00b7 Upper East",
    folder: "images/projects/zaari-2017/",
    images: ["IMG-20171225-WA0024.jpg", "IMG-20171225-WA0025.jpg", "IMG-20171225-WA0026.jpg", "IMG-20171225-WA0027.jpg", "IMG-20171225-WA0028.jpg", "IMG-20171225-WA0029.jpg", "IMG-20171225-WA0030.jpg", "IMG-20171225-WA0031.jpg", "IMG-20171225-WA0032.jpg", "IMG-20171225-WA0033.jpg", "IMG-20171225-WA0034.jpg", "IMG-20171225-WA0035.jpg", "IMG-20171225-WA0036.jpg", "IMG-20171225-WA0037.jpg", "IMG-20171225-WA0038.jpg", "IMG-20171225-WA0039.jpg", "IMG-20171225-WA0040.jpg", "IMG-20171225-WA0041.jpg", "IMG-20171225-WA0042.jpg", "IMG-20171225-WA0043.jpg", "IMG-20171225-WA0044.jpg", "IMG-20171225-WA0045.jpg", "IMG-20171225-WA0046.jpg", "IMG-20171225-WA0047.jpg", "IMG-20171225-WA0048.jpg", "IMG-20171225-WA0049.jpg", "IMG-20171225-WA0050.jpg", "IMG-20171225-WA0051.jpg", "IMG-20171225-WA0052.jpg", "IMG-20171225-WA0053.jpg", "IMG-20171225-WA0054.jpg", "IMG-20171225-WA0055.jpg", "IMG-20171225-WA0056.jpg", "IMG-20171225-WA0057(1).jpg", "IMG-20171225-WA0057.jpg"],
  },

  "yizidug-2018": {
    title:  "Yizidug Basic School",
    meta:   "December 2018 \u00b7 Yizidug, Upper East",
    folder: "images/projects/yizidug-2018/",
    images: ["ANXB1440(1).JPG", "ANXB1440.JPG", "ARNJ3607(1).JPG", "ARNJ3607.JPG", "BZZT5967.JPG", "CDAO8251.JPG", "EOQY9570.JPG", "GCBE4980.JPG", "GYOR3422.JPG", "HQOY1129.JPG", "IITO2870.JPG", "MROK2095.JPG", "NXRC1685.JPG", "ODEA8761.JPG", "QHBM0806.JPG", "QPZW6545.JPG", "QQRL9008.JPG", "SAJL1331.JPG", "TKMO7193.JPG", "UYIY5767.JPG", "VBPH4692.JPG", "VVGO0237.JPG"],
  },

  "nisbuliga-2019": {
    title:  "Nisbuliga Basic School",
    meta:   "July 2019 \u00b7 Nisbuliga, Upper East",
    folder: "images/projects/nisbuliga-2019/",
    images: ["furniture.png"],
  },

  "yizidug-2021": {
    title:  "Yizidug Basic School",
    meta:   "December 2021 \u00b7 Yizidug, Upper East",
    folder: "images/projects/yizidug-2021/",
    images: ["furniture.png"],
  },

  "kpatua-2022": {
    title:  "Kpatua Primary School",
    meta:   "December 2022 \u00b7 Kpatua, Upper East",
    folder: "images/projects/kpatua-2022/",
    images: ["furniture.png"],
  },

  "kpatua-2024": {
    title:  "Kpatua Primary School",
    meta:   "December 2024 \u00b7 Kpatua, Upper East",
    folder: "images/projects/kpatua-2024/",
    images: ["furniture.png"],
  }

};
