"""
generate_gallery_data.py
Run from the root of your project folder:
    python generate_gallery_data.py

Scans images/projects/ and generates js/gallery-data.js automatically.
Run this whenever you add or remove photos from any project folder.
"""

import os
import json

PROJECTS_DIR = os.path.join('images', 'projects')
OUTPUT_FILE  = os.path.join('js', 'gallery-data.js')

IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.webp', '.gif'}

# Project metadata — update if you add a new project folder
METADATA = {
    'kolemasega-2015': {
        'title': 'Kolemasega Basic School',
        'meta':  'December 2015 · Zaari, Upper East',
    },
    'frafra-2016': {
        'title': 'Frafra Catholic School',
        'meta':  'July 2016 · Frafra, Upper East',
    },
    'zaari-2017': {
        'title': 'Zaari Primary School',
        'meta':  'December 2017 · Upper East',
    },
    'yizidug-2018': {
        'title': 'Yizidug Basic School',
        'meta':  'December 2018 · Yizidug, Upper East',
    },
    'nisbuliga-2019': {
        'title': 'Nisbuliga Basic School',
        'meta':  'July 2019 · Nisbuliga, Upper East',
    },
    'yizidug-2021': {
        'title': 'Yizidug Basic School',
        'meta':  'December 2021 · Yizidug, Upper East',
    },
    'kpatua-2022': {
        'title': 'Kpatua Primary School',
        'meta':  'December 2022 · Kpatua, Upper East',
    },
    'kpatua-2024': {
        'title': 'Kpatua Primary School',
        'meta':  'December 2024 · Kpatua, Upper East',
    },
}

def get_images(folder_path):
    files = sorted([
        f for f in os.listdir(folder_path)
        if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS
    ])
    return files

def generate():
    if not os.path.isdir(PROJECTS_DIR):
        print(f'Error: {PROJECTS_DIR} not found. Run setup_gallery.py first.')
        return

    entries = []

    for project_key in METADATA.keys():
        folder_path = os.path.join(PROJECTS_DIR, project_key)
        if not os.path.isdir(folder_path):
            continue

        images = get_images(folder_path)

        if project_key not in METADATA:
            print(f'Warning: no metadata for "{project_key}" — skipping.')
            continue

        meta  = METADATA[project_key]
        entry = (
            f"  {json.dumps(project_key)}: {{\n"
            f"    title:  {json.dumps(meta['title'])},\n"
            f"    meta:   {json.dumps(meta['meta'])},\n"
            f"    folder: {json.dumps(f'images/projects/{project_key}/')},\n"
            f"    images: {json.dumps(images)},\n"
            f"  }}"
        )
        entries.append(entry)
        print(f'✓ {project_key} — {len(images)} image(s)')

    output = (
        "// AUTO-GENERATED by generate_gallery_data.py\n"
        "// Do not edit manually. Run the script to regenerate.\n\n"
        "const GALLERY_DATA = {\n\n"
        + ',\n\n'.join(entries)
        + "\n\n};\n"
    )

    with open(OUTPUT_FILE, 'w') as f:
        f.write(output)

    print(f'\nWrote {OUTPUT_FILE}')

if __name__ == '__main__':
    generate()